services:
  nginx:
    image: nginx
    ports:
      - "5050:5050"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  app1:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5051:5050"
  app2:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5052:5050"