version: '3.8'

services:
  user_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD", "pg_isready -U $${POSTGRES_USER}"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 10
  nginx:
    image: nginx
    ports:
      - "5050:5050"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    restart: always
  app1:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5051:5050"
    depends_on:
      - user_db
  app2:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5052:5050"
    depends_on:
      - user_db
