services:
  nginx:
    image: nginx
    ports:
      - "5050:5050"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  app1:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5051:5050"
    depends_on:
      - user_db
  app2:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5052:5050"
    depends_on:
      - user_db
  user_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
